/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0oDcKwizUSJ
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="container mx-auto px-4 md:px-6 lg:px-8 py-12 grid grid-cols-1 lg:grid-cols-2 gap-8">
      <div className="flex flex-col items-center justify-center">
        <Card className="w-full max-w-md mx-auto">
          <CardHeader>
            <CardTitle>Contenido Destacado</CardTitle>
          </CardHeader>
          <CardContent>
            <img
              alt="Imagen Destacada"
              className="w-full h-64 object-cover rounded-md"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <p className="mt-4 text-center text-gray-600 dark:text-gray-400">
              Este es un contenido destacado. Puede contener información importante o interesante.
            </p>
          </CardContent>
        </Card>
      </div>
      <div className="flex flex-col items-center justify-center">
        <Card className="w-full max-w-md mx-auto">
          <CardHeader>
            <CardTitle>Bienvenido</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-center text-gray-600 dark:text-gray-400">
              Estamos encantados de tenerte aquí. Haz clic en el botón de abajo para comenzar tu viaje.
            </p>
            <div className="mt-4 flex justify-center">
              <Button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Comenzar</Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
